-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 16:54:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbmotel
-- -----------------------------------------------------
-- Residencia la sede.

-- -----------------------------------------------------
-- Schema dbmotel
--
-- Residencia la sede.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbmotel` DEFAULT CHARACTER SET utf8 ;
USE `dbmotel` ;

-- -----------------------------------------------------
-- Table `dbmotel`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmotel`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Cedula` INT NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `Telefono` INT NULL,
  `Direccion` VARCHAR(30) NULL,
  `Activo` TINYINT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmotel`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmotel`.`Habitacion` (
  `idHabitacion` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbmotel`.`Alquiler_Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmotel`.`Alquiler_Habitacion` (
  `idAlquiler_Habitacion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idHabitacion` INT NOT NULL,
  `Precio` DOUBLE NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Hora_Entrada` TIME NOT NULL,
  `Hora_Salida` TIME NULL,
  `Activo` TINYINT NOT NULL,
  PRIMARY KEY (`idAlquiler_Habitacion`),
  INDEX `Fk_Alquiler_Habitacion_Usuario_idx` (`idUsuario` ASC),
  INDEX `Fk_Alquiler_Habitacion_Habitacion_idx` (`idHabitacion` ASC),
  CONSTRAINT `Fk_Alquiler_Habitacion_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbmotel`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Alquiler_Habitacion_Habitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `dbmotel`.`Habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
